quarkus:
  http:
    cors:
      enabled: true
      origins: "*"
      methods: "GET,POST,PUT,DELETE"
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://postgres:5432/pokemon
      username: admin
      password: password
  flyway:
    migrate-at-start: true
  redis:
    hosts: redis://redis:6379

  grpc:
    server:
      port: 9000
  micrometer:
    export:
      prometheus:
        enabled: true
  otel:
    enabled: true
    exporter:
      otlp:
        traces:
          endpoint: "http://otel-collector:4317"

mp:
  jwt:
     verify:
      issuer: "https://github.com/wiormiw"

smallrye:
  jwt:
    verify:
      secretkey: "supersecretkey1234567890123456"
    time-to-live: 3600 # 1 hour in seconds