services:
  app:
    build:
      context: ../../../../
      dockerfile: src/main/resources/docker/Dockerfile
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      - postgres
      - redis
      - otel-collector
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-config.yml:/etc/otel/config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"