global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from the Quarkus application
  - job_name: "pokemon-api"
    metrics_path: "/q/metrics"  # Default Quarkus Micrometer metrics endpoint
    static_configs:
      - targets: ["app:8080"]
        labels:
          app: "pokemon-api"
          instance: "app"

  # Scrape metrics from the OpenTelemetry Collector
  - job_name: "otel-collector"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["otel-collector:8889"]  # Default OTEL Collector metrics port
        labels:
          app: "otel-collector"
          instance: "otel-collector"

  # Scrape metrics from Jaeger
  - job_name: "jaeger"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["jaeger:14269"]  # Jaeger metrics endpoint
        labels:
          app: "jaeger"
          instance: "jaeger"

  # Scrape Prometheus' own metrics (self-monitoring)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
          instance: "prometheus"